@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title RutaFlex - Component Diagram

Container_Boundary(api, "Backend API") {

    Component(usuarios, "Gestión de Usuarios", "Componente")
    Component(viajes, "Gestión de Viajes", "Componente")
    Component(comunicacion, "Comunicación", "Componente")
    Component(historial, "Historial y Reputación", "Componente")
}

Rel(viajes, comunicacion, "Coordina viajes")
Rel(viajes, historial, "Registra actividad")

@enduml