@startuml
left to right direction
skinparam packageStyle rectangle

title Diagrama de Caso de Uso de Sistema - RutaFlex

actor "Pasajero" as Pasajero
actor "Conductor" as Conductor

rectangle "RutaFlex App" {
  usecase "Autenticarse" as UC1
  usecase "Buscar viajes" as UC2
  usecase "Ver detalles\ndel viaje" as UC3
  usecase "Publicar ruta" as UC4
  usecase "Editar ruta" as UC5
  usecase "Chatear" as UC6
  usecase "Enviar mensajes" as UC7
  usecase "Calificar usuarios" as UC8
  usecase "Ver historial" as UC9
  usecase "Ver ahorro" as UC10
  usecase "Editar perfil" as UC11
  usecase "Cerrar sesión" as UC12
  usecase "Compartir ubicación" as UC13
  usecase "Validar identidad" as UC14
  usecase "Recibir notificaciones" as UC15
}

Pasajero --> UC1
Pasajero --> UC2
Pasajero --> UC3
Pasajero --> UC6
Pasajero --> UC7
Pasajero --> UC8
Pasajero --> UC9
Pasajero --> UC10
Pasajero --> UC11
Pasajero --> UC12
Pasajero --> UC13
Pasajero --> UC14
Pasajero --> UC15

Conductor --> UC1
Conductor --> UC4
Conductor --> UC5
Conductor --> UC6
Conductor --> UC7
Conductor --> UC8
Conductor --> UC9
Conductor --> UC10
Conductor --> UC11
Conductor --> UC12
Conductor --> UC13
Conductor --> UC14
Conductor --> UC15
@enduml