@startuml "Business Case: RutaFlex"
left to right direction

actor/ "Estudiante conductor" <<Business Worker>> as Driver
actor/ "Estudiante pasajero" <<Business Worker>> as Passenger

usecase/ "Gestionar\nviajes compartidos" as BUC1
usecase/ "Publicar\nruta" as BUC2
usecase/ "Buscar\nviaje" as BUC3
usecase/ "Coordinar\ntrayecto" as BUC4
usecase/ "Valorar\nexperiencia" as BUC5
usecase/ "Consultar\nhistorial y ahorro" as BUC7

Driver --> BUC1
Passenger --> BUC1

Driver --> BUC2
Passenger --> BUC3
Driver --> BUC4
Passenger --> BUC4

Driver --> BUC5
Passenger --> BUC5


Passenger --> BUC7
Driver --> BUC7

BUC2 --> BUC1 : <<include>>
BUC3 --> BUC1 : <<include>>
BUC4 --> BUC1 : <<include>>
BUC5 --> BUC1 : <<include>>
BUC7 --> BUC1 : <<include>>

skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam Arrow {
  Color #7A1631
}

@enduml