
@startuml
title Diagrama de Caso de Uso de Negocio del producto de software - RutaFlex

skinparam packageStyle rectangle

actor "Estudiante pasajero" as Pasajero
actor "Estudiante conductor" as Conductor

rectangle "Negocio: Buscar Viaje" {
  usecase "Buscar viajes\npor destino" as UC1
  usecase "Filtrar por hora" as UC2
  usecase "Ver detalles\ndel viaje" as UC3
  usecase "Consultar reputación" as UC4
  usecase "Contactar conductor" as UC5
}

Pasajero --> UC1
Pasajero --> UC2
Pasajero --> UC3
Pasajero --> UC4
Pasajero --> UC5

Conductor --> UC4
Conductor --> UC5
@enduml
