@startuml
skinparam componentStyle rectangle

title Diagrama de Componentes - RutaFlex

component "App Móvil RutaFlex" as Mobile
component "Frontend Web RutaFlex" as Web
component "API Gateway" as API
component "Servicio de Usuarios" as Users
component "Servicio de Viajes" as Trips
component "Servicio de Comunicación" as Comm
component "Servicio de Seguridad e Historial" as SecHist
database "Base de Datos" as DB
component "Servicio de Correo\nInstitucional" as Mail
component "Servicio de Notificaciones" as Push
component "Servicio de Mapas / Ubicación" as Maps

Mobile --> API
Web --> API
API --> Users
API --> Trips
API --> Comm
API --> SecHist
Users --> DB
Trips --> DB
Comm --> DB
SecHist --> DB
Users --> Mail
Comm --> Push
Trips --> Maps
Comm --> Maps
@enduml