@startuml "Ecosistema de Casos de Uso - RutaFlex DDD"

left to right direction

actor "Estudiante Pasajero" as Passenger
actor "Estudiante Conductor" as Driver
actor "Administrador" as Admin

actor "Servicio de Correo\nInstitucional" as EmailService
actor "Servicio de Mapas\n(Google Maps)" as MapsService

rectangle "Fronteras del Sistema RutaFlex" {

  rectangle "Contexto: Gestión de Usuarios" {
    usecase "Autenticar Identidad" as UC1
    usecase "Actualizar Atributos del Perfil" as UC2
    usecase "Moderar Cuentas y Permisos" as UC10
  }

  rectangle "Contexto: Gestión de Viajes" {
    usecase "Explorar Itinerarios" as UC3
    usecase "Publicar Ruta de Viaje" as UC4
    usecase "Monitorear Flujo de Cupos" as UC5
  }

  rectangle "Contexto: Comunicación" {
    usecase "Intercambiar Mensajes en Chat" as UC6
  }

  rectangle "Contexto: Seguridad e Historial" {
    usecase "Emitir Calificación de Experiencia" as UC7
    usecase "Inspeccionar Historial de Trayectos" as UC8
    usecase "Auditar Indicadores de Ahorro y CO2" as UC9
  }
}

Passenger -- UC1
Passenger -- UC2
Passenger -- UC3
Passenger -- UC5
Passenger -- UC6
Passenger -- UC7
Passenger -- UC8
Passenger -- UC9

Driver -- UC1
Driver -- UC2
Driver -- UC4
Driver -- UC5
Driver -- UC6
Driver -- UC7
Driver -- UC8
Driver -- UC9

Admin -- UC10

UC1 ..> EmailService : <<use>>
UC4 ..> MapsService : <<use>>
UC3 ..> MapsService : <<use>>

@enduml