@startuml
title Modelo Conceptual - RutaFlex

class Usuario
class Perfil
class CredencialInstitucional
class Sesion

class Estudiante
class Pasajero
class Conductor

class Ruta
class Viaje
class ReservaViaje
class Ubicacion

class Chat
class Mensaje
class Notificacion

class HistorialViaje
class Calificacion
class Ahorro
class ValidacionIdentidad

Estudiante --|> Usuario
Pasajero --|> Estudiante
Conductor --|> Estudiante

Usuario "1" -- "1" Perfil : tiene
Usuario "1" -- "1" CredencialInstitucional : valida
Usuario "1" -- "0..*" Sesion : inicia

Conductor "1" -- "0..*" Ruta : publica

Ruta "1" -- "0..*" Viaje : contiene
Ruta "1" -- "1" Ubicacion : origen/destino

Pasajero "1" -- "0..*" ReservaViaje : realiza
ReservaViaje "0..*" -- "1" Viaje : reserva

Viaje "1" -- "1" Chat : genera

Conductor "1" -- "0..*" Chat : participa
Pasajero "0..*" -- "0..*" Chat : participa

Chat "1" -- "0..*" Mensaje : contiene
Chat "1" -- "0..*" Notificacion : genera

Viaje "1" -- "1" HistorialViaje : genera

HistorialViaje "1" -- "0..*" Calificacion : registra
HistorialViaje "1" -- "0..*" Ahorro : calcula

ValidacionIdentidad "1" -- "0..*" HistorialViaje : valida

@enduml