@startuml ""

package Comunicacion {

    package AgregadoChat {

        class Chat <<AggregateRoot>> {
            - ChatId: id
            - ViajeId: viajeId
        }

        class ChatId <<ValueObject>> {
            - Long: valor
        }

        class Mensaje <<Entity>> {
            - MensajeId: id
            - UsuarioId: remitenteId
            - ContenidoMensaje: contenido
        }

        class MensajeId <<ValueObject>> {
            - Long: valor
        }

        class ContenidoMensaje <<ValueObject>> {
            - String: valor
        }

        class Notificacion <<Entity>> {
            - NotificacionId: id
            - String: tipo
        }

        class NotificacionId <<ValueObject>> {
            - Long: valor
        }
    }
}

package Compartido {

    class UsuarioId <<ValueObject>> {
        - Long: valor
    }

    class ViajeId <<ValueObject>> {
        - Long: valor
    }

}

Chat --> ChatId
Chat --> ViajeId

Chat "1" *--> "1..*" Mensaje
Chat "1" *--> "*" Notificacion

Mensaje --> MensajeId
Mensaje --> ContenidoMensaje
Mensaje --> UsuarioId

Notificacion --> NotificacionId

@enduml