@startuml
skinparam classAttributeIconSize 0

title Bounded Context - Gestión de Usuario

abstract class Usuario {
  +id: UUID
  +nombres: String
  +apellidos: String
  +correoInstitucional: String
  +telefono: String
  +estado: String
}

class Estudiante
class Pasajero
class Conductor

class Perfil {
  +foto: String
  +bio: String
  +universidad: String
}

class CredencialInstitucional {
  +dominio: String
  +validada: boolean
  +fechaValidacion: Date
}

class Sesion {
  +token: String
  +fechaInicio: DateTime
  +fechaFin: DateTime
}

Usuario <|-- Estudiante
Estudiante <|-- Pasajero
Estudiante <|-- Conductor

Usuario "1" o-- "1" Perfil
Usuario "1" o-- "1" CredencialInstitucional
Usuario "1" o-- "0..*" Sesion
@enduml