@startuml ""

package GestionViajes {

    package AgregadoViaje {

        class Viaje <<AggregateRoot>> {
            - ViajeId: id
            - ConductorId: conductorId
            - Ruta: ruta
        }

        class ViajeId <<ValueObject>> {
            - Long: valor
        }

        class ConductorId <<ValueObject>> {
            - Long: valor
        }

        class Ruta <<Entity>> {
            - RutaId: id
            - Ubicacion: origen
            - Ubicacion: destino
            - DateTime: horaSalida
        }

        class RutaId <<ValueObject>> {
            - Long: valor
        }

        class Ubicacion <<ValueObject>> {
            - String: direccion
        }

        class DisponibilidadAsientos <<Entity>> {
            - Integer: asientosDisponibles
        }
    }
}

package Compartido {

    class UsuarioId <<ValueObject>> {
        - Long: valor
    }

}

Viaje --> ViajeId
Viaje --> ConductorId

Viaje "1" *--> "1" Ruta
Viaje "1" *--> "1" DisponibilidadAsientos

Ruta --> RutaId
Ruta --> Ubicacion

@enduml