@startuml ""

package GestionUsuarios {

    package AgregadoUsuario {

        class Usuario <<AggregateRoot>> {
            - UsuarioId: id
            - NombreCompleto: nombre
            - CorreoInstitucional: correo
            - NumeroTelefono: telefono
        }

        class UsuarioId <<ValueObject>> {
            - Long: valor
        }

        class NombreCompleto <<ValueObject>> {
            - String: nombres
            - String: apellidos
        }

        class CorreoInstitucional <<ValueObject>> {
            - String: valor
        }

        class NumeroTelefono <<ValueObject>> {
            - String: valor
        }

        class Perfil <<Entity>> {
            - PerfilId: id
            - String: biografia
            - String: fotoPerfil
        }

        class PerfilId <<ValueObject>> {
            - Long: valor
        }

        class CredencialInstitucional <<Entity>> {
            - CredencialId: id
            - Boolean: validada
        }

        class CredencialId <<ValueObject>> {
            - Long: valor
        }
    }
}

Usuario --> UsuarioId
Usuario --> NombreCompleto
Usuario --> CorreoInstitucional
Usuario --> NumeroTelefono

Usuario "1" *--> "1" Perfil
Usuario "1" *--> "1" CredencialInstitucional

Perfil --> PerfilId
CredencialInstitucional --> CredencialId

@enduml