@startuml ""

package SeguridadHistorial {

    package AgregadoCalificacion {

        class Calificacion <<AggregateRoot>> {
            - CalificacionId: id
            - UsuarioCalificadoId: usuarioCalificadoId
            - Puntaje: puntaje
        }

        class CalificacionId <<ValueObject>> {
            - Long: valor
        }

        class UsuarioCalificadoId <<ValueObject>> {
            - Long: valor
        }

        class Puntaje <<ValueObject>> {
            - Integer: valor
        }
    }

    package AgregadoHistorialViajes {

        class HistorialViajes <<AggregateRoot>> {
            - HistorialId: id
            - UsuarioId: usuarioId
        }

        class HistorialId <<ValueObject>> {
            - Long: valor
        }

        class RegistroViaje <<Entity>> {
            - RegistroViajeId: id
            - ViajeId: viajeId
        }

        class RegistroViajeId <<ValueObject>> {
            - Long: valor
        }

        class Ahorro <<Entity>> {
            - AhorroId: id
            - Decimal: monto
        }

        class AhorroId <<ValueObject>> {
            - Long: valor
        }

        class AhorroCO2 <<Entity>> {
            - AhorroCO2Id: id
            - Decimal: kilogramos
        }

        class AhorroCO2Id <<ValueObject>> {
            - Long: valor
        }
    }
}

package Compartido {

    class UsuarioId <<ValueObject>> {
        - Long: valor
    }

    class ViajeId <<ValueObject>> {
        - Long: valor
    }

}

Calificacion --> CalificacionId
Calificacion --> UsuarioCalificadoId
Calificacion --> Puntaje

HistorialViajes --> HistorialId
HistorialViajes --> UsuarioId

HistorialViajes "1" *--> "*" RegistroViaje
HistorialViajes "1" *--> "*" Ahorro
HistorialViajes "1" *--> "*" AhorroCO2

RegistroViaje --> RegistroViajeId
RegistroViaje --> ViajeId

Ahorro --> AhorroId
AhorroCO2 --> AhorroCO2Id

@enduml